// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories": {
            "post": {
                "description": "Creates a new product category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Create a new category",
                "parameters": [
                    {
                        "description": "Category data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/views.CreateNewCategory"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/views.CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/customer-cards": {
            "post": {
                "description": "Creates a new customer discount card and stores it in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerCard"
                ],
                "summary": "Create a new customer card",
                "parameters": [
                    {
                        "description": "Customer card data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/views.CreateNewCustomerCard"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/views.CustomerCardResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "views.CategoryResponse": {
            "type": "object",
            "properties": {
                "category_name": {
                    "type": "string"
                },
                "category_number": {
                    "type": "integer"
                }
            }
        },
        "views.CreateNewCategory": {
            "type": "object",
            "required": [
                "category_name"
            ],
            "properties": {
                "category_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                }
            }
        },
        "views.CreateNewCustomerCard": {
            "type": "object",
            "required": [
                "card_number",
                "customer_name",
                "customer_percent",
                "customer_surname",
                "phone_number"
            ],
            "properties": {
                "card_number": {
                    "type": "string",
                    "maxLength": 13,
                    "minLength": 1
                },
                "city": {
                    "type": "string",
                    "maxLength": 50
                },
                "customer_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "customer_patronymic": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "customer_percent": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "customer_surname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 13
                },
                "street": {
                    "type": "string",
                    "maxLength": 50
                },
                "zipcode": {
                    "type": "string",
                    "maxLength": 9
                }
            }
        },
        "views.CustomerCardResponse": {
            "type": "object",
            "properties": {
                "card_number": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "customer_name": {
                    "type": "string"
                },
                "customer_patronymic": {
                    "type": "string"
                },
                "customer_percent": {
                    "type": "integer"
                },
                "customer_surname": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "zipcode": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Go server API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
