// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories": {
            "get": {
                "description": "Retrieves all product categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Get all categories",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "sorted",
                        "name": "sorted",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "category_number",
                        "name": "category_number",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "category_name",
                        "name": "category_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/views.CategoryResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new product category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Create a new category",
                "parameters": [
                    {
                        "description": "Category data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/views.CreateNewCategory"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Payload of category",
                        "schema": {
                            "$ref": "#/definitions/views.CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/categories/{id}": {
            "get": {
                "description": "Retrieves an existing product category by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Get a category by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/views.CategoryResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing product category by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Update an existing category",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload of category",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/views.UpdateCategory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/views.CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an existing product category by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Delete a category",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/checks": {
            "get": {
                "description": "Retrieves all checks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Checks"
                ],
                "summary": "Get all checks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sorted",
                        "name": "employee_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "category_number",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "category_name",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/views.CheckListResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Checks"
                ],
                "summary": "Create a new check",
                "parameters": [
                    {
                        "description": "Check data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/views.CreateNewCheck"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/views.CheckResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/checks/price": {
            "get": {
                "description": "Retrieves total price of checks of all or specific cashier within date rage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Checks"
                ],
                "summary": "Get total price of checks of all or specific cashier within date rage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sorted",
                        "name": "employee_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "category_number",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "category_name",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": {
                                    "type": "number",
                                    "format": "float64"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/checks/{checkNumber}": {
            "get": {
                "description": "Get a check by check number with products list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Checks"
                ],
                "summary": "Get a check by check number with products list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Check number",
                        "name": "checkNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/views.CheckResponseWithProducts"
                        }
                    },
                    "404": {
                        "description": "Entity not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing check by check number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Checks"
                ],
                "summary": "Delete a check by check number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Check number",
                        "name": "checkNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Entity not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/customer-cards": {
            "get": {
                "description": "Retrieves a list of all customer discount cards",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerCard"
                ],
                "summary": "List all customer cards",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "percent",
                        "name": "percent",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "sorted",
                        "name": "sorted",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/views.CustomerCardResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new customer discount card and stores it in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerCard"
                ],
                "summary": "Create a new customer card",
                "parameters": [
                    {
                        "description": "Customer card data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/views.CreateNewCustomerCard"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/views.CustomerCardResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/customer-cards/{cardNumber}": {
            "get": {
                "description": "Retrieves a customer discount card by its number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerCard"
                ],
                "summary": "Get a customer card by number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer card number",
                        "name": "cardNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/views.CustomerCardResponse"
                        }
                    },
                    "404": {
                        "description": "Entity not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing customer discount card",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerCard"
                ],
                "summary": "Update a customer card",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer card number",
                        "name": "cardNumber",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Customer card data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/views.UpdateCustomerCard"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/views.CustomerCardResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Entity not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an existing customer discount card",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerCard"
                ],
                "summary": "Delete a customer card",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer card number",
                        "name": "cardNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Entity not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "views.CategoryResponse": {
            "type": "object",
            "properties": {
                "category_name": {
                    "type": "string"
                },
                "category_number": {
                    "type": "integer"
                }
            }
        },
        "views.CheckListResponse": {
            "type": "object",
            "properties": {
                "check_response": {
                    "$ref": "#/definitions/views.CheckResponse"
                },
                "product": {
                    "$ref": "#/definitions/views.ProductResponse"
                }
            }
        },
        "views.CheckResponse": {
            "type": "object",
            "properties": {
                "card_number": {
                    "type": "string"
                },
                "check_number": {
                    "type": "string"
                },
                "id_employee": {
                    "type": "string"
                },
                "print_date": {
                    "type": "string"
                },
                "sum_total": {
                    "type": "number"
                },
                "vat": {
                    "type": "number"
                }
            }
        },
        "views.CheckResponseWithProducts": {
            "type": "object",
            "properties": {
                "check_response": {
                    "$ref": "#/definitions/views.CheckResponse"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/views.ProductResponse"
                    }
                }
            }
        },
        "views.CreateNewCategory": {
            "type": "object",
            "required": [
                "category_name"
            ],
            "properties": {
                "category_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                }
            }
        },
        "views.CreateNewCheck": {
            "type": "object",
            "required": [
                "card_number",
                "check_number",
                "id_employee",
                "print_date",
                "products",
                "vat"
            ],
            "properties": {
                "card_number": {
                    "type": "string",
                    "maxLength": 13,
                    "minLength": 1
                },
                "check_number": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 1
                },
                "id_employee": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 1
                },
                "print_date": {
                    "type": "string"
                },
                "products": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/views.StoreProduct"
                    }
                },
                "vat": {
                    "type": "number",
                    "maximum": 999999999.9999,
                    "minimum": 0
                }
            }
        },
        "views.CreateNewCustomerCard": {
            "type": "object",
            "required": [
                "card_number",
                "customer_name",
                "customer_percent",
                "customer_surname",
                "phone_number"
            ],
            "properties": {
                "card_number": {
                    "type": "string",
                    "maxLength": 13,
                    "minLength": 1
                },
                "city": {
                    "type": "string",
                    "maxLength": 50
                },
                "customer_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "customer_patronymic": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "customer_percent": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "customer_surname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 13
                },
                "street": {
                    "type": "string",
                    "maxLength": 50
                },
                "zipcode": {
                    "type": "string",
                    "maxLength": 9
                }
            }
        },
        "views.CustomerCardResponse": {
            "type": "object",
            "properties": {
                "card_number": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "customer_name": {
                    "type": "string"
                },
                "customer_patronymic": {
                    "type": "string"
                },
                "customer_percent": {
                    "type": "integer"
                },
                "customer_surname": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "zipcode": {
                    "type": "string"
                }
            }
        },
        "views.ProductResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "selling_price": {
                    "type": "number"
                }
            }
        },
        "views.StoreProduct": {
            "type": "object",
            "required": [
                "quantity",
                "upc"
            ],
            "properties": {
                "quantity": {
                    "type": "integer",
                    "minimum": 1
                },
                "upc": {
                    "type": "string",
                    "maxLength": 12,
                    "minLength": 1
                }
            }
        },
        "views.UpdateCategory": {
            "type": "object",
            "required": [
                "category_name"
            ],
            "properties": {
                "category_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                }
            }
        },
        "views.UpdateCustomerCard": {
            "type": "object",
            "required": [
                "customer_name",
                "customer_percent",
                "customer_surname",
                "phone_number"
            ],
            "properties": {
                "city": {
                    "type": "string",
                    "maxLength": 50
                },
                "customer_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "customer_patronymic": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "customer_percent": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "customer_surname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 13
                },
                "street": {
                    "type": "string",
                    "maxLength": 50
                },
                "zipcode": {
                    "type": "string",
                    "maxLength": 9
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Go server API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
