TRUNCATE TABLE sale RESTART IDENTITY CASCADE;
TRUNCATE TABLE checks RESTART IDENTITY CASCADE;
TRUNCATE TABLE store_product RESTART IDENTITY CASCADE;
TRUNCATE TABLE product RESTART IDENTITY CASCADE;
TRUNCATE TABLE customer_card RESTART IDENTITY CASCADE;
TRUNCATE TABLE employee RESTART IDENTITY CASCADE;
TRUNCATE TABLE category RESTART IDENTITY CASCADE;